language: python
python: "3.6"

env:
  - GIT_REPO=none

install:
  - pip3 install -r requirements.txt

stages:
  - test

jobs:
  include:
    - stage: test
      script: 
        - git clone $GIT_REPO
        - python3 -m unittest discover -p *_test.py

notifications:
  email: true