language: python
python: "3.6"
sudo: required

install:
  - pip3 install -r requirements.txt

stages:
  - test

jobs:
  include:
    - stage: test
      script: 
        - python3 -m unittest discover -p *_test.py

notifications:
  email: true