# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
        environment:
          GIT_REPO: https://github.com/demid5111/test-smart-edu-ci
          HASH: c90f0bc7fadd153c4a15b4f3b56b63d6afb6bc10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: clone repo
          command: |
            git clone $GIT_REPO tmp
            cd tmp
            git reset --hard $HASH
            cd ..
            mv tmp/* .
            ls -la
      
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python3 -m unittest discover -p *_test.py 

      - store_artifacts:
          path: test-reports
          destination: test-reports
          